/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-05-18 01:09:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#headDiv h1 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#noticeDiv{\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write(".star {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#profileBtn{\r\n");
      out.write("\tmargin-top:20px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#submitTr {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label.is-invalid {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tfont-size: 0.8rem;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- 우편번호 검색 js -->\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script src=\"/resources/js/member/join_form.js?ver=38\" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- validation -->\r\n");
      out.write("<script src=\"/resources/js/common/jquery.validate.js?ver=11\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-sm\">\r\n");
      out.write("\t<div id=\"headDiv\">\r\n");
      out.write("\t\t<h1>JOIN US</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"noticeDiv\">\r\n");
      out.write("\t\t<span class=\"star\">*</span>필수 입력 사항\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<form action=\"/member/insertMember\" method=\"post\" id=\"joinForm\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<table class=\"table table-borderless\">\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>아이디<span class=\"star\">*</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"inputId\" name=\"memId\"></td>\r\n");
      out.write("\t\t\t\t\t<td rowspan=\"4\" id=\"profileTd\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/resources/img/profile/profile_no_image.png\" class=\"img-thumbnail\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"profileBtn\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" value=\"profile_no_image.png\" name=\"memProfileImg\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-outline-dark btn-sm\" id=\"regProfile\">프로필등록</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>비밀번호<span class=\"star\">*</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" class=\"form-control\" id=\"inputPassword\" name=\"memPw\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>비밀번호 확인<span class=\"star\">*</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" class=\"form-control\" id=\"confirm_pw\" name=\"confirm_pw\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>닉네임<span class=\"star\">*</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"inputNickName\" name=\"memNickname\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>전화번호<span class=\"star\">*</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"tel\" class=\"form-control\" id=\"inputTel\" name=\"memTel\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>이메일<span class=\"star\">*</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"email\" class=\"form-control\" id=\"inputEmail\" name=\"memEmail\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>주소<span class=\"star\">*</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"inputAddr\" name=\"memAddr\" placeholder=\"주소를 입력하시려면 이 곳을 클릭해주세요 (도로명주소)\" onclick=\"openPostCode();\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>상세주소</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"inputAddrDetail\" name=\"memAddrDetail\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr id=\"submitTr\">\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\"><button type=\"submit\" class=\"btn btn-primary\">회원가입</button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
