/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-04-23 01:12:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".aaa{\r\n");
      out.write("\tbackground-color: #f8f9fa;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"/resources/js/member/join.js?ver=30\"></script>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/common/jquery.validate.js?ver=02\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"row justify-content-center\">\r\n");
      out.write("<div class=\"col-4 aaa\">\r\n");
      out.write("<form action=\"/member/join\" method=\"post\" id=\"joinForm\">\r\n");
      out.write("\t<div class=\"form-row\">\r\n");
      out.write("\t\t<div class=\"form-group col-md-6\">\r\n");
      out.write("\t\t\t<label for=\"id\">I.D.</label> \r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\"id=\"id\" name=\"id\" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-6\">\r\n");
      out.write("\t\t\t<label for=\"name\">NAME</label> \r\n");
      out.write("\t\t\t<input type=\"text\"class=\"form-control\" id=\"name\" name=\"name\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-row\">\r\n");
      out.write("\t\t<div class=\"form-group col-md-12\">\r\n");
      out.write("\t\t\t<label for=\"password\">PASSWORD</label> \r\n");
      out.write("\t\t\t<input type=\"password\" class=\"form-control\"id=\"password\" name=\"password\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-row\">\r\n");
      out.write("\t\t<div class=\"form-group col-md-12\">\r\n");
      out.write("\t\t\t<label for=\"confirm_pw\">CONFIRM PASSWORD</label> \r\n");
      out.write("\t\t\t<input type=\"password\" class=\"form-control\"id=\"confirm_pw\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-row align-items-end\" >\r\n");
      out.write("\t\t<div class=\"form-group col-md-4\">\r\n");
      out.write("\t\t\t<label for=\"tel1\">TEL</label>\r\n");
      out.write("\t\t\t<select class=\"form-control\" id=\"tel1\" name=\"tels\">\r\n");
      out.write("\t\t\t\t<option value=\"010\">010</option>\r\n");
      out.write("\t\t\t\t<option value=\"011\">011</option>\r\n");
      out.write("\t\t\t\t<option value=\"016\">016</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-4\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"tels\" id=\"tel2\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-4\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"tels\" id=\"tel3\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-row align-items-end\">\r\n");
      out.write("\t\t<div class=\"form-group col-md-8\">\r\n");
      out.write("\t\t\t<label for=\"addr\">ADDRESS</label> \r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\"id=\"addr\" name=\"addr\" readonly onclick=\"openPostCode();\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-4\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"form-control btn btn-primary\" value=\"주소검색\" onclick=\"openPostCode();\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-row\">\r\n");
      out.write("\t\t<div class=\"form-group col-md-12\">\r\n");
      out.write("\t\t\t<label for=\"addrDetail\">DETAIL ADDRESS</label> \r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\"id=\"addrDetail\" name=\"addrDetail\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-row align-items-end\">\r\n");
      out.write("\t\t<div class=\"form-group col-md-6\">\r\n");
      out.write("\t\t\t<label for=\"email\">EMAIL</label> \r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\"id=\"email\" name=\"emails\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-6\">\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write(" \t\t\t\t <div class=\"input-group-prepend\">\r\n");
      out.write("    \t\t\t\t<span class=\"input-group-text\" id=\"basic-addon1\">@</span>\r\n");
      out.write(" \t\t\t\t </div>\r\n");
      out.write("  \t\t\t\t <input type=\"text\" class=\"form-control\" aria-describedby=\"basic-addon1\" name=\"emails\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"form-row\">\r\n");
      out.write("\t\t<label for=\"email\">GENDER</label> \r\n");
      out.write("\t\t<div class=\"form-group col-md-12\">\r\n");
      out.write("\t\t\t<div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t<input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"inlineRadio1\" value=\"M\" checked>\r\n");
      out.write(" \t\t\t\t <label class=\"form-check-label\" for=\"inlineRadio1\">남</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-check form-check-inline\">\r\n");
      out.write("  \t\t\t\t<input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"inlineRadio2\" value=\"F\">\r\n");
      out.write("  \t\t\t\t<label class=\"form-check-label\" for=\"inlineRadio2\">녀</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <button type=\"submit\" class=\"btn btn-primary btn-block\">Join</button>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
